## Correcting coordinates
Since some of the coordinates from Unity were not accurate, they were recalculated and will now be mapped on the final data frame.

In [1]:
import os
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

### Load corrected coordinates
built on script `01_CoordinatesJasons`

In [2]:
CorrectedCoordinates = pd.read_csv('/Volumes/TwoTeras/Resources/AgentCoordinates_short_exp2.csv')
#CorrectedCoordinates = pd.read_csv('/Users/tracysanchezpacheco/Documents/Resources/BuildingCoordinates_short.csv')
CorrectedCoordinates.head()

,Unnamed: 0,AgentCenterWorld.x,AgentCenterWorld.z,Name,AvatarName,PointingTargetBuildingId,AgentID,PointingTargetCondition,Context,Agent
0,0,-122.162125,-135.098068,1_CmAAct,01_Cma,44,1,CmAAct,True,True
1,1,291.670898,54.871109,2_CmAAct,02_Cma,13,2,CmAAct,True,True
2,2,270.361755,-48.999924,3_CmAAct,03_Cma,16,3,CmAAct,True,True
3,3,109.478653,115.749481,4_CmAAct,04_Cma,23,4,CmAAct,True,True
4,4,-6.688904,34.304352,5_CmAAct,05_Cma,5,5,CmAAct,True,True

### Reading the participants data from the participants data reconstruction pipeline

In [3]:
CorrectedCoordinates[['AgentID', 'PointingTargetBuildingId', 'PointingTargetCondition']]

    AgentID  PointingTargetBuildingId PointingTargetCondition
0         1                        44                  CmAAct
1         2                        13                  CmAAct
2         3                        16                  CmAAct
3         4                        23                  CmAAct
4         5                         5                  CmAAct
5         6                         4                   SaAct
6         7                        59                  CmAAct
7         8                        34                  CmAAct
8         9                        32                  CmAAct
9        10                        58                  CmAAct
10       11                        21                  CmAAct
11       12                        52                  CmAAct
12       13                        29                  CmAAct
13       14                        38                  CmAAct
14       15                        54                   SaAct
15       16                        36                   SaAct
16       17                        40                   SaAct
17       18                        48                   SaAct
18       19                        31                   SaAct
19       20                        30                   SaAct
20       21                        49                   SaAct
21       22                        39                   SaAct
22       23                        35                   SaAct
23       24                        11                  CmAAct
24       25                        43                   SaAct
25       26                        33                   SaAct
26       27                        37                   SaAct
27       28                        10                   SaAct
28       29                        50                     CmA
29       30                         3                     CmA
30       31                         2                     CmA
31       32                        51                     CmA
32       33                        20                     CmA
33       34                        41                     CmA
34       35                        42                     CmA
35       36                        57                     CmA
36       37                         8                     CmA
37       38                         9                     CmA
38       39                        47                     CmA
39       40                        14                     CmA
40       41                        27                     CmA
41       42                        45                     CmA
42       43                        55                   SaAct
43       44                        18                      Sa
44       45                        24                      Sa
45       46                        25                      Sa
46       47                        22                      Sa
47       48                        12                      Sa
48       49                        19                      Sa
49       50                        15                      Sa
50       51                        17                      Sa
51       52                        28                      Sa
52       53                         1                      Sa
53       54                        26                      Sa
54       55                         7                      Sa
55       56                         6                      Sa

In [4]:
PointingTask = pd.read_csv('/Volumes/TwoTeras/1_Experiment_2/Pointing_Task/Results/AgentPointingTask.csv')
#PointingTask = pd.read_csv('/Users/tracysanchezpacheco/Documents/PointingTask.csv')
PointingTask.ImageName.astype('category')
PointingTask.ImageName.value_counts()

48_Sa_68_12         109
13_CmAAct_42_29     107
36_CmA_8_57         106
45_Sa_76_24         106
47_Sa_74_22         105
37_CmA_18_8         105
35_CmA_28_42        105
43_Sa_106_55        102
33_CmA_10_20        101
49_Sa_72_19         101
30_CmA_24_3         100
56_Sa_60_6          100
53_Sa_58_1          100
38_CmA_12_9          99
22_SaAct_96_39       99
20_SaAct_84_30       99
42_CmA_16_45         98
29_CmA_14_50         97
32_CmA_22_51         94
40_CmA_0_14          94
19_SaAct_86_31       93
03_CmA_54_16         92
10_CmAAct__38_58     90
41_CmA_20_27         90
21_SaAct_110_49      90
50_Sa_66_15          89
11_CmAAct_50_21      88
54_Sa_80_26          88
16_SaAct_92_36       87
02_CmAAct_46_13      86
26_SaAct_88_33       86
51_Sa_64_17          86
05_CmA_40_5          86
15_SaAct_104_54      86
39_CmA_6_47          83
34_CmA_2_41          81
04_CmAAct_30_23      80
31_CmA_4_2           80
09_CmAAct_44_32      78
23_SaAct_90_35       78
55_Sa_62_7           77
06_SaAct_56_4        77
12_CmAAct_32_52      76
18_SaAct_102_48      75
17_SaAct_98_40       74
14_CmAAct_34_38      74
52_Sa_82_28          73
07_CmAAct_52_59      73
27_SaAct_94_37       71
01_CmAAct_48_44      70
25_SaAct_100_43      68
44_Sa_70_18          68
24_CmAAct_26_11      66
28_SaAct_108_10      63
46_Sa_78_25          62
08_CmAAct_36_34      61
Name: ImageName, dtype: int64

In [5]:
PointingTask.head()

,Unnamed: 0,SubjectID,ParticipantPosition_x,ParticipantPosition_z,PointerPosition_x,PointerPosition_z,PointerDirection_x,PointerDirection_z,PointerDirection_y,TargetBuildingPosition_x,...,StartPointID.1,ID_for_StartingPosition,ImageIndexNumber,ImageName,TimeDelta,RT,TimeOut,TimeStampBegin,TimeStampEnd,Angle
0,0,1031,-61.486801,27.881790,-61.211075,27.538521,0.967161,-0.253698,0.015428,-52.689445,...,1,1,46,16_SaAct_92_36,0 days 00:00:09.057460992,9.057461,False,2022-11-22 14:20:37.039554048,2022-11-22 14:20:46.097015040,72.464104
1,1,1031,-61.538162,27.714478,-61.177170,27.703957,0.974709,0.222339,0.022539,259.692596,...,1,2,33,50_Sa_66_15,0 days 00:00:03.833090560,3.833091,False,2022-11-22 14:20:46.376759040,2022-11-22 14:20:50.209849600,13.981791
2,2,1031,-61.534622,27.724136,-61.363297,27.997902,0.123959,0.991357,0.042962,197.395660,...,1,3,2,31_CmA_4_2,0 days 00:00:03.614850304,3.614850,False,2022-11-22 14:20:50.480170240,2022-11-22 14:20:54.095020544,44.315105
3,3,1031,-61.541702,27.716370,-61.329300,27.528870,0.998588,-0.053040,-0.002889,-7.537856,...,1,4,44,26_SaAct_88_33,0 days 00:00:10.142213888,10.142214,False,2022-11-22 14:20:54.361868544,2022-11-22 14:21:04.504082432,55.778976
4,4,1031,-61.479416,27.702278,-61.055069,27.764542,0.966937,0.255002,0.002622,151.605972,...,1,5,25,11_CmAAct_50_21,0 days 00:00:13.799721984,13.799722,False,2022-11-22 14:21:04.776386304,2022-11-22 14:21:18.576108288,53.836834

In [6]:
CorrectedCoordinates[CorrectedCoordinates['Context'] == False].head()

,Unnamed: 0,AgentCenterWorld.x,AgentCenterWorld.z,Name,AvatarName,PointingTargetBuildingId,AgentID,PointingTargetCondition,Context,Agent
5,5,46.922928,-126.919205,6_SaAct,06_Cma,4,6,SaAct,False,True
14,14,-334.702087,66.975830,15_SaAct,15_Cma,54,15,SaAct,False,True
15,15,-55.071732,-150.303055,16_SaAct,16_Cma,36,16,SaAct,False,True
16,16,-107.858475,129.943878,17_SaAct,17_Cma,40,17,SaAct,False,True
17,17,-194.664444,-137.772018,18_SaAct,18_Cma,48,18,SaAct,False,True

In [7]:
#Merging the updated set of coordinates from new list with final participant data set
#CoordinatesIntegrated = pd.merge(PointingTask, CorrectedCoordinates,
#                                 left_on= ['avatarID' , 'public'],
#                                 right_on=['AgentID','Context'],
#                                 how='outer',
#                                 suffixes= ['_drop','_keep'])
CoordinatesIntegrated = pd.merge(PointingTask, CorrectedCoordinates,
                                 left_on= ['avatarID' , 'meaningful'],
                                 right_on=['AgentID','Context'],
                                 how='outer',
                                 suffixes= ['_drop','_keep'])
CoordinatesIntegrated.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4872 entries, 0 to 4871
Data columns (total 43 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0_drop                4872 non-null   int64
 1   SubjectID                      4872 non-null   int64
 2   ParticipantPosition_x          4872 non-null   float64
 3   ParticipantPosition_z          4872 non-null   float64
 4   PointerPosition_x              4872 non-null   float64
 5   PointerPosition_z              4872 non-null   float64
 6   PointerDirection_x             4872 non-null   float64
 7   PointerDirection_z             4872 non-null   float64
 8   PointerDirection_y             4872 non-null   float64
 9   TargetBuildingPosition_x       4872 non-null   float64
 10  TargetBuildingPosition_z       4872 non-null   float64
 11  DistanceToParticipant          4872 non-null   float64
 12  avatarID                       4872 non-null   int64
 13  AvatarPresence                 4872 non-null   bool
 14  AvatarPresenceCategory         4872 non-null   object
 15  meaningful                     4872 non-null   bool
 16  meaningfulBuilding             4872 non-null   object
 17  activeAgent                    4872 non-null   bool
 18  AgentCategory                  4872 non-null   object
 19  StartPointID                   4872 non-null   int64
 20  PointingTaskStartingLocations  4872 non-null   int64
 21  Trials                         4872 non-null   int64
 22  TrialNumber                    4872 non-null   int64
 23  StartPointID.1                 4872 non-null   int64
 24  ID_for_StartingPosition        4872 non-null   int64
 25  ImageIndexNumber               4872 non-null   int64
 26  ImageName                      4872 non-null   object
 27  TimeDelta                      4872 non-null   object
 28  RT                             4872 non-null   float64
 29  TimeOut                        4872 non-null   bool
 30  TimeStampBegin                 4872 non-null   object
 31  TimeStampEnd                   4872 non-null   object
 32  Angle                          4872 non-null   float64
 33  Unnamed: 0_keep                4872 non-null   int64
 34  AgentCenterWorld.x             4872 non-null   float64
 35  AgentCenterWorld.z             4872 non-null   float64
 36  Name                           4872 non-null   object
 37  AvatarName                     4872 non-null   object
 38  PointingTargetBuildingId       4872 non-null   int64
 39  AgentID                        4872 non-null   int64
 40  PointingTargetCondition        4872 non-null   object
 41  Context                        4872 non-null   bool
 42  Agent                          4872 non-null   bool
dtypes: bool(6), float64(14), int64(13), object(10)
memory usage: 1.4+ MB

In [8]:
CoordinatesIntegrated.groupby(['SubjectID', 'TrialNumber']).count()

                       Unnamed: 0_drop  ParticipantPosition_x  \
SubjectID TrialNumber
1031      1                          1                      1
          2                          1                      1
          3                          1                      1
          4                          1                      1
          5                          1                      1
...                                ...                    ...
9627      164                        1                      1
          165                        1                      1
          166                        1                      1
          167                        1                      1
          168                        1                      1

                       ParticipantPosition_z  PointerPosition_x  \
SubjectID TrialNumber
1031      1                                1                  1
          2                                1                  1
          3                                1                  1
          4                                1                  1
          5                                1                  1
...                                      ...                ...
9627      164                              1                  1
          165                              1                  1
          166                              1                  1
          167                              1                  1
          168                              1                  1

                       PointerPosition_z  PointerDirection_x  \
SubjectID TrialNumber
1031      1                            1                   1
          2                            1                   1
          3                            1                   1
          4                            1                   1
          5                            1                   1
...                                  ...                 ...
9627      164                          1                   1
          165                          1                   1
          166                          1                   1
          167                          1                   1
          168                          1                   1

                       PointerDirection_z  PointerDirection_y  \
SubjectID TrialNumber
1031      1                             1                   1
          2                             1                   1
          3                             1                   1
          4                             1                   1
          5                             1                   1
...                                   ...                 ...
9627      164                           1                   1
          165                           1                   1
          166                           1                   1
          167                           1                   1
          168                           1                   1

                       TargetBuildingPosition_x  TargetBuildingPosition_z  \
SubjectID TrialNumber
1031      1                                   1                         1
          2                                   1                         1
          3                                   1                         1
          4                                   1                         1
          5                                   1                         1
...                                         ...                       ...
9627      164                                 1                         1
          165                                 1                         1
          166                                 1                         1
          167                                 1                         1
          168                                 1                         1

                       ...  Unnamed: 0_keep  AgentCenterWorld.x  \
SubjectID TrialNumber  ...
1031      1            ...                1                   1
          2            ...                1                   1
          3            ...                1                   1
          4            ...                1                   1
          5            ...                1                   1
...                    ...              ...                 ...
9627      164          ...                1                   1
          165          ...                1                   1
          166          ...                1                   1
          167          ...                1                   1
          168          ...                1                   1

                       AgentCenterWorld.z  Name  AvatarName  \
SubjectID TrialNumber
1031      1                             1     1           1
          2                             1     1           1
          3                             1     1           1
          4                             1     1           1
          5                             1     1           1
...                                   ...   ...         ...
9627      164                           1     1           1
          165                           1     1           1
          166                           1     1           1
          167                           1     1           1
          168                           1     1           1

                       PointingTargetBuildingId  AgentID  \
SubjectID TrialNumber
1031      1                                   1        1
          2                                   1        1
          3                                   1        1
          4                                   1        1
          5                                   1        1
...                                         ...      ...
9627      164                                 1        1
          165                                 1        1
          166                                 1        1
          167                                 1        1
          168                                 1        1

                       PointingTargetCondition  Context  Agent
SubjectID TrialNumber
1031      1                                  1        1      1
          2                                  1        1      1
          3                                  1        1      1
          4                                  1        1      1
          5                                  1        1      1
...                                        ...      ...    ...
9627      164                                1        1      1
          165                                1        1      1
          166                                1        1      1
          167                                1        1      1
          168                                1        1      1

[4872 rows x 41 columns]

In [9]:
CoordinatesIntegrated.rename(columns={"AgentCenterWorld.z": "AgentCenterWorld_z", "AgentCenterWorld.x": "AgentCenterWorld_x"}, inplace=True)

In [10]:
CoordinatesIntegrated = CoordinatesIntegrated[['SubjectID',
                                               'ParticipantPosition_x', 'ParticipantPosition_z',
                                               'PointerPosition_x','PointerPosition_z',
                                               'PointerDirection_x', 'PointerDirection_z',
                                               'AgentCenterWorld_z', 'AgentCenterWorld_x', 'DistanceToParticipant',
                                               'PointingTaskStartingLocations','AgentID', 'Name',
                                               'StartPointID','PointingTargetCondition', 'Context', 'Agent', 'avatarID','AvatarPresence', 
                                               'AvatarPresenceCategory', 'meaningful','meaningfulBuilding',
                                               'activeAgent', 'AgentCategory',
                                               'Trials', 'TrialNumber', 'StartPointID' ,'ID_for_StartingPosition','ImageName',
                                               'TimeDelta','RT', 'TimeOut', 'TimeStampBegin', 'TimeStampEnd']]
#CoordinatesIntegrated = CoordinatesIntegrated[['SubjectID',
#                                               'ParticipantPosition_x', 'ParticipantPosition_z',
#                                               'PointerPosition_x','PointerPosition_z',
#                                               'PointerDirection_x', 'PointerDirection_z',
#                                               'AgentCenterWorld_z', 'AgentCenterWorld_x', 'DistanceToParticipant',
#                                               'PointingTaskStartingLocations','AgentID', 'Name',
#                                               'StartPointID','PointingTargetCondition', 'Context', 'Agent', 'avatarID','AvatarPresence', 'AvatarPresenceCategory', 'public','BuildingCategory',
#                                               'activeAgent', 'AgentCategory',
#                                               'Trials', 'TrialNumber', 'StartPointID' ,'ID_for_StartingPosition','ImageName',
#                                               'TimeDelta','RT', 'TimeOut', 'TimeStampBegin', 'TimeStampEnd']]

In [11]:
CoordinatesIntegrated.drop_duplicates(subset=['SubjectID', 'TrialNumber'], inplace=True)
CoordinatesIntegrated.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4872 entries, 0 to 4871
Data columns (total 34 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   SubjectID                      4872 non-null   int64
 1   ParticipantPosition_x          4872 non-null   float64
 2   ParticipantPosition_z          4872 non-null   float64
 3   PointerPosition_x              4872 non-null   float64
 4   PointerPosition_z              4872 non-null   float64
 5   PointerDirection_x             4872 non-null   float64
 6   PointerDirection_z             4872 non-null   float64
 7   AgentCenterWorld_z             4872 non-null   float64
 8   AgentCenterWorld_x             4872 non-null   float64
 9   DistanceToParticipant          4872 non-null   float64
 10  PointingTaskStartingLocations  4872 non-null   int64
 11  AgentID                        4872 non-null   int64
 12  Name                           4872 non-null   object
 13  StartPointID                   4872 non-null   int64
 14  PointingTargetCondition        4872 non-null   object
 15  Context                        4872 non-null   bool
 16  Agent                          4872 non-null   bool
 17  avatarID                       4872 non-null   int64
 18  AvatarPresence                 4872 non-null   bool
 19  AvatarPresenceCategory         4872 non-null   object
 20  meaningful                     4872 non-null   bool
 21  meaningfulBuilding             4872 non-null   object
 22  activeAgent                    4872 non-null   bool
 23  AgentCategory                  4872 non-null   object
 24  Trials                         4872 non-null   int64
 25  TrialNumber                    4872 non-null   int64
 26  StartPointID                   4872 non-null   int64
 27  ID_for_StartingPosition        4872 non-null   int64
 28  ImageName                      4872 non-null   object
 29  TimeDelta                      4872 non-null   object
 30  RT                             4872 non-null   float64
 31  TimeOut                        4872 non-null   bool
 32  TimeStampBegin                 4872 non-null   object
 33  TimeStampEnd                   4872 non-null   object
dtypes: bool(6), float64(10), int64(9), object(9)
memory usage: 1.1+ MB

In [12]:
CoordinatesIntegrated[['AvatarPresence', 'AvatarPresenceCategory', 'ImageName']]

      AvatarPresence AvatarPresenceCategory       ImageName
0              False                Present  16_SaAct_92_36
1              False                Present  16_SaAct_92_36
2              False                Present  16_SaAct_92_36
3              False                Present  16_SaAct_92_36
4              False                Present  16_SaAct_92_36
...              ...                    ...             ...
4867           False                Present     46_Sa_78_25
4868           False                Present     46_Sa_78_25
4869           False                Present     46_Sa_78_25
4870           False                Present     46_Sa_78_25
4871           False                Present     46_Sa_78_25

[4872 rows x 3 columns]

In [13]:
# Added cell to set Working Directory to your location
os.chdir('/Volumes/TwoTeras/1_Experiment_2/Pointing_Task/Results')
os.getcwd()

'/Volumes/TwoTeras/1_Experiment_2/Pointing_Task/Results'

In [14]:
CoordinatesIntegrated[['ImageName', 'avatarID']]

           ImageName  avatarID
0     16_SaAct_92_36        16
1     16_SaAct_92_36        16
2     16_SaAct_92_36        16
3     16_SaAct_92_36        16
4     16_SaAct_92_36        16
...              ...       ...
4867     46_Sa_78_25        46
4868     46_Sa_78_25        46
4869     46_Sa_78_25        46
4870     46_Sa_78_25        46
4871     46_Sa_78_25        46

[4872 rows x 2 columns]

In [15]:
CoordinatesIntegrated.to_csv('AgentPointingTask_Integrated.csv')